line-length = 99
ignore = [
    "PLR2004",
    "D104",
    "D107",
    "C901",
    "PT001",
    "PT023",
    "UP036",
]
exclude = ["venv*"]
select = [
    "B",   # bandit
    "C",   # complexity
    "D",   # docstrings
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "PT",  # flake8-pytest
    "RUF", # ruff base config
    "SIM", # flake-simplify
    "UP",  # pyupgrade
    "W",   # pycodestyle warnings
    "YTT", # flake8-2020
    # "ARG", # flake8-unused args
]
[pydocstyle]
convention = "pep257"
[flake8-unused-arguments]
ignore-variadic-names = true
